import { useMemo } from "react";
import { planLayout, type LayoutResult, type PlacedDevice } from "@/lib/layout";
import { encode, type BlueprintData, type BlueprintHeader, type BlueprintArea, type PlacedBuilding, type Vec3, type Vec2i } from "@/lib/blueprint";
import { getBuildingSize } from "@/lib/layout";
import type { CalcResult, CalcNode } from "@/lib/calc";

export interface UseBlueprintReturn {
  /** The layout result from planLayout() */
  layoutResult: LayoutResult | null;
  /** Encoded DSP blueprint string */
  blueprintString: string | null;
  /** The BlueprintData used for encoding */
  blueprintData: BlueprintData | null;
}

/**
 * Convert a CalcNode to a LayoutNode expected by planLayout().
 */
function toLayoutNode(node: CalcNode): { buildingId: number; buildingCount: number; recipeId: number; depth: number } {
  return {
    buildingId: node.buildingId,
    buildingCount: node.buildingCount,
    recipeId: node.recipeId,
    depth: node.depth,
  };
}

/**
 * Convert grid position to blueprint Vec3 coordinates.
 * DSP blueprints use XZ-plane: x→x, y→0 (height), z→y
 */
function gridPosToVec3(x: number, y: number): Vec3 {
  return { x, y: 0, z: y };
}

/**
 * Convert PlacedDevice to PlacedBuilding for blueprint encoding.
 */
function placedDeviceToBuilding(device: PlacedDevice, index: number): PlacedBuilding {
  const size = getBuildingSize(device.buildingId);
  const pos = gridPosToVec3(device.position.x, device.position.y);
  const end = gridPosToVec3(
    device.position.x + size.width,
    device.position.y + size.height,
  );

  return {
    index,
    itemId: device.buildingId,
    modelIndex: 0,
    areaIndex: 0,
    localOffset: [pos, end],
    yaw: [(2 * Math.PI * device.rotation) / 4, 0],
    tilt: 0,
    pitch: 0,
    tilt2: 0,
    pitch2: 0,
    outputObjIdx: -1,
    inputObjIdx: -1,
    outputToSlot: 1,
    inputFromSlot: 1,
    outputFromSlot: 1,
    inputToSlot: 1,
    outputOffset: 0,
    inputOffset: 0,
    recipeId: device.recipeId,
    filterId: 0,
    parameters: null,
    content: "",
  };
}

/**
 * Build a BlueprintData from a LayoutResult.
 */
function buildBlueprintData(layout: LayoutResult): BlueprintData {
  const header: BlueprintHeader = {
    layout: 10,
    icons: [0, 0, 0, 0, 0],
    time: new Date(),
    gameVersion: "0.10.28.20711",
    shortDesc: "Generated by DSQBPG",
    author: "DSQBPG",
    customVersion: "",
    externalFields: "",
    desc: "DSP Blueprint generated from calculator",
  };

  const buildings: PlacedBuilding[] = layout.devices.map((d, i) =>
    placedDeviceToBuilding(d, i),
  );

  const area: BlueprintArea = {
    index: 0,
    parentIndex: -1,
    tropicAnchor: 0,
    areaSegments: 200,
    anchorLocalOffset: { x: 0, y: 0 },
    size: {
      x: Math.ceil(layout.totalWidth) + 2,
      y: Math.ceil(layout.totalHeight) + 2,
    },
  };

  return {
    header,
    version: 1,
    cursorOffset: { x: 0, y: 0 },
    cursorTargetArea: 0,
    dragBoxSize: { x: 0, y: 0 },
    primaryAreaIdx: 0,
    areas: [area],
    buildings,
    patch: 0,
    reformData: null,
  };
}

/**
 * Hook that converts a CalcResult into layout and blueprint representations.
 * Returns null for all fields when input is null.
 */
export function useBlueprint(calcResult: CalcResult | null): UseBlueprintReturn {
  return useMemo(() => {
    if (!calcResult || calcResult.nodes.length === 0) {
      return { layoutResult: null, blueprintString: null, blueprintData: null };
    }

    const layoutNodes = calcResult.nodes.map(toLayoutNode);
    const layoutResult = planLayout(layoutNodes);

    if (layoutResult.devices.length === 0) {
      return { layoutResult, blueprintString: null, blueprintData: null };
    }

    const blueprintData = buildBlueprintData(layoutResult);
    let blueprintString: string | null = null;
    try {
      blueprintString = encode(blueprintData);
    } catch {
      blueprintString = null;
    }

    return { layoutResult, blueprintString, blueprintData };
  }, [calcResult]);
}
